-- Replace synthetic segment-ID availability with short-lived, explainable
-- heuristic snapshots generated by the estimate-parking-availability function.

begin;

create extension if not exists pgcrypto with schema extensions;
set local search_path = public, extensions, pg_temp;

create table public.parking_availability_estimates (
  id uuid primary key default gen_random_uuid(),
  segment_id uuid not null references public.parking_segments(id) on delete cascade,
  availability_percent integer,
  available_spaces integer,
  status text not null,
  confidence text not null,
  estimator_version text not null,
  generated_at timestamptz not null,
  valid_until timestamptz not null,
  context_hash text not null,
  factor_summary jsonb not null default '[]'::jsonb,
  destination_place_id text,
  destination_category text,
  destination_is_open boolean,
  traffic_ratio double precision,
  created_at timestamptz not null default now(),
  constraint parking_availability_percent_range
    check (availability_percent between 0 and 100),
  constraint parking_available_spaces_nonnegative
    check (available_spaces >= 0),
  constraint parking_estimate_status_allowed
    check (status in ('estimated', 'unknown')),
  constraint parking_estimate_confidence_allowed
    check (confidence in ('low', 'medium')),
  constraint parking_estimate_window_valid
    check (valid_until >= generated_at),
  constraint parking_estimate_context_hash_valid
    check (context_hash ~ '^[0-9a-f]{64}$'),
  constraint parking_estimate_factors_are_array
    check (jsonb_typeof(factor_summary) = 'array'),
  constraint parking_estimate_values_match_status
    check (
      (status = 'estimated' and availability_percent is not null and available_spaces is not null)
      or
      (status = 'unknown' and availability_percent is null and available_spaces is null)
    ),
  constraint parking_estimate_context_unique
    unique (segment_id, context_hash, estimator_version)
);

create index parking_availability_estimates_segment_generated_idx
  on public.parking_availability_estimates (segment_id, generated_at desc);
create index parking_availability_estimates_valid_until_idx
  on public.parking_availability_estimates (valid_until);
create index parking_availability_estimates_context_valid_idx
  on public.parking_availability_estimates
  (context_hash, estimator_version, valid_until desc);

alter table public.parking_availability_estimates enable row level security;
revoke all on table public.parking_availability_estimates from public, anon, authenticated;

comment on table public.parking_availability_estimates is
  'Short-lived deterministic heuristic snapshots. Values are estimates, not observations or live occupancy.';
comment on column public.parking_availability_estimates.destination_place_id is
  'Google Place ID only; raw Google Places responses are not persisted.';
comment on column public.parking_availability_estimates.valid_until is
  'Estimator cache validity, not observation freshness.';

drop function if exists public.fetch_parking_cells(
  double precision,
  double precision,
  double precision,
  double precision,
  text
);
drop view if exists public.parking_zone_summaries;
drop view if exists public.parking_segment_summaries;

create view public.parking_segment_summaries
with (security_barrier = true)
as
select
  segment.id::text as id,
  segment.parking_zone_id,
  segment.strasse as street_name,
  segment.prm_name as source_area_name,
  segment.lat,
  segment.lon,
  segment.angebot as capacity,
  estimate.available_spaces as estimated_available_capacity,
  estimate.availability_percent as estimated_availability_percent,
  coalesce(estimate.status, 'unknown') as availability_status,
  estimate.confidence as availability_confidence,
  estimate.generated_at as estimate_generated_at,
  estimate.valid_until as estimate_valid_until,
  estimate.estimator_version,
  estimate.factor_summary as estimate_factors,
  case
    when concat_ws(
      ' ',
      segment.parkregel_gruppe,
      segment.parkregel_name,
      segment.parkregel_beschreibung
    ) ~* '\m(kostenlos|gebührenfrei|gebuhrenfrei|entgeltfrei|free)\M' then 'free'
    when concat_ws(
      ' ',
      segment.parkregel_gruppe,
      segment.parkregel_name,
      segment.parkregel_beschreibung
    ) ~* '\m(kurzzeitparken|mischparken|altstadt|kostenpflichtig|paid)\M' then 'paid'
    else 'unknown'
  end as pricing_status,
  case
    when segment.parkregel_gruppe like 'Kurzzeitparken%' then 2.5
    when segment.parkregel_gruppe like 'Mischparken%' then 2.0
    when segment.parkregel_gruppe like 'Altstadt%' then 3.0
    else null
  end::double precision as hourly_rate,
  segment.parkregel_beschreibung as regulation_description,
  segment.parkregel_gruppe as regulation_group_name,
  segment.parkregel_name as regulation_name,
  segment.geoportal_class,
  segment.updated_at
from public.parking_segments as segment
left join lateral (
  select
    snapshot.available_spaces,
    snapshot.availability_percent,
    snapshot.status,
    snapshot.confidence,
    snapshot.generated_at,
    snapshot.valid_until,
    snapshot.estimator_version,
    snapshot.factor_summary
  from public.parking_availability_estimates as snapshot
  where snapshot.segment_id = segment.id
    and snapshot.valid_until > now()
  order by snapshot.generated_at desc, snapshot.created_at desc
  limit 1
) as estimate on true
where segment.location is not null;

create view public.parking_zone_summaries
with (security_barrier = true)
as
select
  zone.id::text as zone_id,
  coalesce(nullif(btrim(zone.name), ''), 'Unnamed parking zone') as zone_name,
  zone.status as source_status,
  st_y(st_pointonsurface(zone.geom)) as representative_latitude,
  st_x(st_pointonsurface(zone.geom)) as representative_longitude,
  count(segment.id)::integer as segment_count,
  case
    when count(segment.capacity) = 0 then null
    else sum(segment.capacity)::bigint
  end as total_capacity,
  sum(segment.estimated_available_capacity)::bigint as available_capacity,
  case
    when coalesce(
      sum(segment.capacity) filter (
        where segment.availability_status = 'estimated'
          and segment.capacity > 0
      ),
      0
    ) <= 0 then null
    else round(
      100.0 * sum(segment.estimated_available_capacity)
      / nullif(
        sum(segment.capacity) filter (
          where segment.availability_status = 'estimated'
            and segment.capacity > 0
        ),
        0
      )
    )::integer
  end as availability_percent,
  min(segment.hourly_rate) filter (
    where segment.pricing_status = 'paid' and segment.hourly_rate is not null
  ) as minimum_hourly_rate,
  max(segment.hourly_rate) filter (
    where segment.pricing_status = 'paid' and segment.hourly_rate is not null
  ) as maximum_hourly_rate,
  coalesce(bool_or(segment.pricing_status = 'free'), false) as has_free_parking,
  coalesce(bool_or(segment.pricing_status = 'unknown'), false) as has_unknown_pricing,
  case
    when count(segment.id) filter (
      where segment.availability_status = 'estimated'
    ) = 0 then 'unknown'
    when count(segment.id) filter (
      where segment.availability_status = 'estimated'
    ) = count(segment.id) then 'estimated'
    else 'mixed'
  end as availability_status,
  count(segment.id) filter (
    where segment.availability_status = 'estimated'
  )::integer as estimated_segment_count,
  count(segment.id) filter (
    where segment.availability_status <> 'estimated'
  )::integer as unknown_segment_count,
  case
    when count(segment.id) = 0 then 0
    else round(
      count(segment.id) filter (
        where segment.availability_status = 'estimated'
      )::numeric / count(segment.id),
      4
    )::double precision
  end as estimate_coverage_ratio,
  min(segment.estimate_generated_at) filter (
    where segment.availability_status = 'estimated'
  ) as oldest_estimate_generated_at,
  max(segment.estimate_generated_at) filter (
    where segment.availability_status = 'estimated'
  ) as newest_estimate_generated_at,
  max(segment.updated_at) as updated_at
from public.parking_zones as zone
left join public.parking_segment_summaries as segment
  on segment.parking_zone_id = zone.id
where zone.geom is not null
group by zone.id, zone.name, zone.status, zone.geom;

create function public.fetch_parking_cells(
  p_min_lng double precision,
  p_min_lat double precision,
  p_max_lng double precision,
  p_max_lat double precision,
  p_resolution text,
  p_context_hash text
)
returns table (
  id text,
  parent_zone_ids text[],
  center_latitude double precision,
  center_longitude double precision,
  min_lng double precision,
  min_lat double precision,
  max_lng double precision,
  max_lat double precision,
  resolution text,
  segment_count integer,
  total_capacity bigint,
  available_capacity bigint,
  availability_percent integer,
  minimum_hourly_rate double precision,
  maximum_hourly_rate double precision,
  has_free_parking boolean,
  has_unknown_pricing boolean,
  availability_status text,
  estimated_segment_count integer,
  unknown_segment_count integer,
  estimate_coverage_ratio double precision,
  oldest_estimate_generated_at timestamptz,
  newest_estimate_generated_at timestamptz,
  updated_at timestamptz
)
language sql
stable
security definer
set search_path = public, extensions, pg_temp
as $$
  with request as (
    select
      case p_resolution
        when 'coarse' then 500.0
        when 'fine' then 250.0
        else null
      end as cell_size,
      st_transform(
        st_makeenvelope(p_min_lng, p_min_lat, p_max_lng, p_max_lat, 4326),
        3857
      ) as bounds
    where p_min_lng < p_max_lng
      and p_min_lat < p_max_lat
      and p_min_lng between -180 and 180
      and p_max_lng between -180 and 180
      and p_min_lat between -90 and 90
      and p_max_lat between -90 and 90
      and (p_context_hash is null or p_context_hash ~ '^[0-9a-f]{64}$')
  ),
  cells as (
    select
      grid.i,
      grid.j,
      grid.geom,
      st_transform(grid.geom, 4326) as geom_4326
    from request
    cross join lateral st_hexagongrid(request.cell_size, request.bounds) as grid
    where request.cell_size is not null
      and st_intersects(grid.geom, request.bounds)
  ),
  cell_assignments as (
    select
      cell.i,
      cell.j,
      cell.geom_4326,
      source_segment.id as segment_id,
      row_number() over (
        partition by source_segment.id order by cell.i, cell.j
      ) as cell_rank
    from cells as cell
    join public.parking_segments as source_segment
      on source_segment.location && cell.geom_4326
     and st_covers(cell.geom_4326, source_segment.location)
  ),
  segment_values as (
    select
      assignment.i,
      assignment.j,
      assignment.geom_4326,
      segment.id,
      segment.parking_zone_id,
      segment.angebot as capacity,
      segment.updated_at,
      case
        when concat_ws(
          ' ',
          segment.parkregel_gruppe,
          segment.parkregel_name,
          segment.parkregel_beschreibung
        ) ~* '\m(kostenlos|gebührenfrei|gebuhrenfrei|entgeltfrei|free)\M' then 'free'
        when concat_ws(
          ' ',
          segment.parkregel_gruppe,
          segment.parkregel_name,
          segment.parkregel_beschreibung
        ) ~* '\m(kurzzeitparken|mischparken|altstadt|kostenpflichtig|paid)\M' then 'paid'
        else 'unknown'
      end as pricing_status,
      case
        when segment.parkregel_gruppe like 'Kurzzeitparken%' then 2.5
        when segment.parkregel_gruppe like 'Mischparken%' then 2.0
        when segment.parkregel_gruppe like 'Altstadt%' then 3.0
        else null
      end::double precision as hourly_rate,
      estimate.available_spaces,
      estimate.availability_percent,
      estimate.status as estimate_status,
      estimate.generated_at
    from cell_assignments as assignment
    join public.parking_segments as segment on segment.id = assignment.segment_id
    left join lateral (
      select
        snapshot.available_spaces,
        snapshot.availability_percent,
        snapshot.status,
        snapshot.generated_at
      from public.parking_availability_estimates as snapshot
      where snapshot.segment_id = segment.id
        and snapshot.context_hash = p_context_hash
        and snapshot.valid_until > now()
      order by snapshot.generated_at desc, snapshot.created_at desc
      limit 1
    ) as estimate on true
    where assignment.cell_rank = 1
  ),
  aggregates as (
    select
      value.i,
      value.j,
      value.geom_4326,
      count(value.id)::integer as segment_count,
      array_agg(distinct value.parking_zone_id::text)
        filter (where value.parking_zone_id is not null) as parent_zone_ids,
      sum(value.capacity)::bigint as total_capacity,
      sum(value.available_spaces) filter (
        where value.estimate_status = 'estimated'
      )::bigint as available_capacity,
      sum(value.capacity) filter (
        where value.estimate_status = 'estimated' and value.capacity > 0
      )::bigint as estimated_capacity,
      min(value.hourly_rate) filter (
        where value.pricing_status = 'paid'
      ) as minimum_hourly_rate,
      max(value.hourly_rate) filter (
        where value.pricing_status = 'paid'
      ) as maximum_hourly_rate,
      coalesce(bool_or(value.pricing_status = 'free'), false) as has_free_parking,
      coalesce(bool_or(value.pricing_status = 'unknown'), false) as has_unknown_pricing,
      count(value.id) filter (
        where value.estimate_status = 'estimated'
      )::integer as estimated_segment_count,
      min(value.generated_at) filter (
        where value.estimate_status = 'estimated'
      ) as oldest_estimate_generated_at,
      max(value.generated_at) filter (
        where value.estimate_status = 'estimated'
      ) as newest_estimate_generated_at,
      max(value.updated_at) as updated_at
    from segment_values as value
    group by value.i, value.j, value.geom_4326
  )
  select
    concat(p_resolution, ':', aggregate.i, ':', aggregate.j) as id,
    coalesce(aggregate.parent_zone_ids, array[]::text[]) as parent_zone_ids,
    st_y(st_centroid(aggregate.geom_4326)) as center_latitude,
    st_x(st_centroid(aggregate.geom_4326)) as center_longitude,
    st_xmin(box3d(aggregate.geom_4326)) as min_lng,
    st_ymin(box3d(aggregate.geom_4326)) as min_lat,
    st_xmax(box3d(aggregate.geom_4326)) as max_lng,
    st_ymax(box3d(aggregate.geom_4326)) as max_lat,
    p_resolution as resolution,
    aggregate.segment_count,
    aggregate.total_capacity,
    aggregate.available_capacity,
    case
      when coalesce(aggregate.estimated_capacity, 0) <= 0 then null
      else round(
        100.0 * aggregate.available_capacity
        / nullif(aggregate.estimated_capacity, 0)
      )::integer
    end as availability_percent,
    aggregate.minimum_hourly_rate,
    aggregate.maximum_hourly_rate,
    aggregate.has_free_parking,
    aggregate.has_unknown_pricing,
    case
      when aggregate.estimated_segment_count = 0 then 'unknown'
      when aggregate.estimated_segment_count = aggregate.segment_count then 'estimated'
      else 'mixed'
    end as availability_status,
    aggregate.estimated_segment_count,
    aggregate.segment_count - aggregate.estimated_segment_count
      as unknown_segment_count,
    round(
      aggregate.estimated_segment_count::numeric
      / nullif(aggregate.segment_count, 0),
      4
    )::double precision as estimate_coverage_ratio,
    aggregate.oldest_estimate_generated_at,
    aggregate.newest_estimate_generated_at,
    aggregate.updated_at
  from aggregates as aggregate
  order by aggregate.i, aggregate.j
  limit 400;
$$;

grant select on public.parking_segment_summaries to anon, authenticated;
grant select on public.parking_zone_summaries to anon, authenticated;
revoke all on function public.fetch_parking_cells(
  double precision,
  double precision,
  double precision,
  double precision,
  text,
  text
) from public;
grant execute on function public.fetch_parking_cells(
  double precision,
  double precision,
  double precision,
  double precision,
  text,
  text
) to anon, authenticated;

comment on view public.parking_segment_summaries is
  'Parking inventory with the newest non-expired heuristic snapshot; no segment-ID hash fallback.';
comment on view public.parking_zone_summaries is
  'Capacity-weighted newest-snapshot zone estimates with explicit estimate coverage.';
comment on function public.fetch_parking_cells(
  double precision,
  double precision,
  double precision,
  double precision,
  text,
  text
) is
  'Context-specific semantic-zoom cells; unknown segments are excluded from the availability denominator.';

commit;
